# Configuration par défaut pour les modèles DeepLabV3+

# Configuration pour DeepLabV3+ de base
deeplabv3_plus:
  model_type: "deeplabv3_plus"
  model_params:
    in_channels: 1
    out_channels: 1
    encoder_channels: [64, 128, 256, 512]
    aspp_channels: 256
    decoder_channels: 256
    dropout_rate: 0.2
    use_cbam: false

# Configuration pour DeepLabV3+ avec conditionnement par seuil
deeplabv3_plus_threshold:
  model_type: "deeplabv3_plus_threshold"
  model_params:
    in_channels: 1
    out_channels: 1
    encoder_channels: [64, 128, 256, 512]
    aspp_channels: 256
    decoder_channels: 256
    threshold_encoding_dim: 128
    dropout_rate: 0.2
    use_cbam: true
    use_pos_encoding: true

# Configuration pour DeepLabV3+ avec CBAM
deeplabv3_plus_cbam:
  model_type: "deeplabv3_plus"
  model_params:
    in_channels: 1
    out_channels: 1
    encoder_channels: [64, 128, 256, 512]
    aspp_channels: 256
    decoder_channels: 256
    dropout_rate: 0.2
    use_cbam: true 